/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ListIndexLazyImport = createFileRoute('/list/')()
const ListCreateIndexLazyImport = createFileRoute('/list/create/')()
const ListIdIndexLazyImport = createFileRoute('/list/$id/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ListIndexLazyRoute = ListIndexLazyImport.update({
  path: '/list/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/list/index.lazy').then((d) => d.Route))

const ListCreateIndexLazyRoute = ListCreateIndexLazyImport.update({
  path: '/list/create/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/list/create/index.lazy').then((d) => d.Route),
)

const ListIdIndexLazyRoute = ListIdIndexLazyImport.update({
  path: '/list/$id/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/list/$id/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/list/': {
      preLoaderRoute: typeof ListIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/list/$id/': {
      preLoaderRoute: typeof ListIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/list/create/': {
      preLoaderRoute: typeof ListCreateIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ListIndexLazyRoute,
  ListIdIndexLazyRoute,
  ListCreateIndexLazyRoute,
])

/* prettier-ignore-end */
